name: fitfusion_pro
description: AI-powered fitness platform mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Charts and Analytics
  fl_chart: ^0.65.0
  
  # Camera and Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  
  # Animation
  lottie: ^2.7.0
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Video Player
  video_player: ^2.8.1
  
  # File Picker
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 